--  DDL for table ACCOUNT 

CREATE TABLE ACCOUNT 
  (ACCOUNT_ID VARCHAR2 (50 BYTE) CONSTRAINT "ACCOUNT_ID_NN" NOT NULL ENABLE, 
   FIRST_NAME VARCHAR2 (30 BYTE) CONSTRAINT "FIRST_NAME_NN" NOT NULL ENABLE,
   LAST_NAME VARCHAR2 (30 BYTE) CONSTRAINT "LAST_NAME_NN" NOT NULL ENABLE, 
   COUNTRY VARCHAR2 (10 BYTE) CONSTRAINT "COUNTRY_NN" NOT NULL ENABLE,
   CONSTRAINT "ACCOUNT_ID_PK" PRIMARY KEY (ACCOUNT_ID))
TABLESPACE "USERS";
   
--  DDL for table CREDIT_CARD 

CREATE TABLE CREDIT_CARD
(CREDIT_CARD_ID NUMBER (12) CONSTRAINT "CREDIT_CARD_ID_NN" NOT NULL ENABLE,
 ACCOUNT_ID VARCHAR2 (50 BYTE) CONSTRAINT "CARD_ACCOUNT_ID_NN" NOT NULL ENABLE,
 CASH_AMOUNT NUMBER, 
 CONSTRAINT "CREDIT_CARD_ID_PK" PRIMARY KEY (CREDIT_CARD_ID),
 CONSTRAINT "ACCOUNT_ID_FK" FOREIGN KEY (ACCOUNT_ID) REFERENCES BANK.ACCOUNT (ACCOUNT_ID) ENABLE)
TABLESPACE "USERS";
 
--  DDL for table TRANSACTION

CREATE TABLE TRANSACTION
(TRANSACTION_ID NUMBER CONSTRAINT "TRANSACTION_ID_NN" NOT NULL ENABLE,
 TRANSACTION_DATE DATE CONSTRAINT "TRANSACTION_DATE_NN" NOT NULL ENABLE,
 FROM_CREDIT_CARD NUMBER (12) CONSTRAINT "FROM_CRED_CARD_NN" NOT NULL ENABLE,
 TO_CREDIT_CARD NUMBER (12) CONSTRAINT "TO_CRED_CARD" NOT NULL ENABLE,
 AMMOUNT NUMBER CONSTRAINT "TRANS_AMMOUNT_NN" NOT NULL ENABLE,
 CONSTRAINT "TRANSACTION_ID_PK" PRIMARY KEY (TRANSACTION_ID),
 CONSTRAINT "FROM_CARD_FK" FOREIGN KEY (FROM_CREDIT_CARD) REFERENCES CREDIT_CARD (CREDIT_CARD_ID) ENABLE,
 CONSTRAINT "TO_CARD_FK" FOREIGN KEY (TO_CREDIT_CARD) REFERENCES CREDIT_CARD (CREDIT_CARD_ID) ENABLE,
 CONSTRAINT "AMMOUNT_MIN" CHECK (AMMOUNT > 0) ENABLE)
TABLESPACE "USERS";
 




















